### ISSUE TITLE
Windows Defender block on update 3.8.0.283

### ISSUE THREAD

**Issue by TMCupcake** [EQAditu/AdvancedCombatTracker#107]
When downloading the latest update via the ACT interface, Windows Defender detects a trojan Win32/Phonzy.A!ml on download completion which it then seeks to quarantine or remove, preventing the update of ACT.

**Comment by BenEng11037** [comment]
I got this as well, with this message.
![image](https://github.com/user-attachments/assets/25cf1c9e-50a6-4a4f-9266-f4e3ccb10cd6)

**Comment by EQAditu** [comment]
Any detection that says `!ml` in it means Machine Learning... in other words, AI.  The same buzzword that says to use Elmer's Glue to thicken pizza sauce and to consume rocks daily.

![unnamed](https://github.com/user-attachments/assets/1f0f5bda-a167-4fa1-90cb-7441e4570dff)

There's not a lot that I can do aside from create another(meaningless) update that will possibly give a different detection.

**Comment by BenEng11037** [comment]
Thanks for responding. I guess I will try to figure out how to let it bypass win defender and do the update.

**Comment by EQAditu** [comment]
You can just use the setup installer.  It will do very similar things except it may re-add shortcuts, if you deleted them.

**Comment by EQAditu** [comment]
Microsoft's tracker says a specific definition version will clear the detection...

![image](https://github.com/user-attachments/assets/91566032-253a-4119-8678-a780e31a10a9)

**Comment by Ginko-sensei** [comment]
I just updated it without Windows Defender blocking anything, seems to be fixed on their side.

**Comment by EQAditu** [comment]
Closing this since the detection hasn't happened for days and 283 is no longer the latest version available.
