### ISSUE TITLE
The contents of the zip file (v3.4.5.266) are missing.

### ISSUE THREAD

**Issue by TamaZooo** [EQAditu/AdvancedCombatTracker#11]
The contents of v3.4.5.266 are missing.

Contents of ACTv3.zip
- ACTx86.exe
- ACTx86.exe.config
- Advanced Combat Tracker.exe
- Advanced Combat Tracker.exe.config

**Comment by EQAditu** [comment]
I'm not really sure why that part of the release process started with an empty ZIP to update with new files.  Anyways, I merged it with the last version's ZIP.
