### ISSUE TITLE
Allow shortcut to enable/disable overlay out of combat.

### ISSUE THREAD

**Issue by Makpptfox** [EQAditu/AdvancedCombatTracker#112]
Hi, first: this is an improvement proposition and not an issue in any regards.

I've looked around in the shortcuts for the plugins, and while it is possible to show/hide the overlay, activate/disable the overlay, even block/unblock or allow/disable click through I do not see any shortcut to enable/disable the hiding out of combat overlay option.

It would be great for situations where you just want the overlay to works in combat and disappear once done but still want to check something real quick after a fight, you could then just disable the auto fading of the overlay while out of combat without having to activate/disable it everytime you get into an encounter if I were to use the already implemented activate/disable or show/hide shortcut.

I searched around in the issues, closed or open, and seen nothing or the sort being asked, so I figured I might ask if it is possible or not.

Regards. 👍

**Comment by EQAditu** [comment]
If you're talking about OverlayPlugin, you should raise the issue there.
https://github.com/OverlayPlugin/OverlayPlugin

**Comment by Makpptfox** [comment]
My bad, will do.
