### ISSUE TITLE
Cannot view Encounter Logs

### ISSUE THREAD

**Issue by omegasrevenge** [EQAditu/AdvancedCombatTracker#13]
When clicking on "View Logs", it opens an empty window. It started happening at some point a year or so ago. Except for this, ACT seems to be working perfectly fine.
![1f8ef189a0ef4dd0d43313b83776bc98](https://user-images.githubusercontent.com/2969706/72860388-f16f0f00-3cc6-11ea-8353-db1a40e3cf56.png)
![aregageragerager](https://user-images.githubusercontent.com/2969706/72860548-6c382a00-3cc7-11ea-9891-3acf01c4863c.png)

**Comment by omegasrevenge** [comment]
After asking in the FFXIV Parsing Plugin Discord, people helped me.
For some random reason that I don't understand, the file Advanced Combat Tracker.config.xml had this line 
`<Form Name="FormEncounterLogs" X="0" Y="0" W="130" H="60" WindowState="Normal" />`
And editing it to 
`<Form Name="FormEncounterLogs" X="0" Y="0" W="1300" H="600" WindowState="Normal" />`
fixed the problem. I do not know why it was so small in the first place. Having it that small made it impossible to resize the window using the mouse as well.

**Comment by EQAditu** [comment]
FYI, regardless of size, there are always resize handles...
![image](https://user-images.githubusercontent.com/52854036/72864061-c40f6a80-3ca0-11ea-88d1-6c4650bc6d06.png)
You can also force resizing with the window menu.  (click the icon, or press Alt then Down, or right-click the mouse-over preview you're showing in the taskbar)
![image](https://user-images.githubusercontent.com/52854036/72864212-413adf80-3ca1-11ea-8b7e-1bbc167bd680.png)

Without knowing what you normally do on your computer, it's hard to say what caused it.  For example, it being on a secondary monitor that is no longer there.  A display driver update quickly resizing windows.  Etc.
