### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by LeapingLizzy** [EQAditu/AdvancedCombatTracker#15]
Hi, I encounter the below error when trying to open ACT. 

Grateful for any help. Thanks!

![image](https://user-images.githubusercontent.com/60247537/73042279-1bcae480-3e0d-11ea-8b20-ec895e81bc84.png)

**Comment by EQAditu** [comment]
I can't really give much advice for the Hojoring plugin or any plugin made by anoyetta.  If you need to resolve this specific problem, then remove the plugin.

PS.  This isn't really a troubleshooting forum.

**Comment by LeapingLizzy** [comment]
Okie, sorry.
