### ISSUE TITLE
Cactbot DPS not working as expected.

### ISSUE THREAD

**Issue by cototheburn** [EQAditu/AdvancedCombatTracker#26]
![image](https://user-images.githubusercontent.com/37516115/93008448-b9ad2400-f542-11ea-9d11-0036ec66a22e.png)

In a dungeon and it only shows one boss fight dps out of the whole dungeon and I have the reset at 300 seconds.

**Comment by EQAditu** [comment]
I have no idea what you're trying to show me.  If you're trying to show a problem with ACT, show a screenshot of ACT.  I don't play FFXIV; I don't know what random overlays look like vs what FFXIV looks like.

If you think it's a problem with something else(like Cactbot in your title), go there...
https://github.com/ravahn/FFXIV_ACT_Plugin
https://github.com/ngld/OverlayPlugin
https://github.com/quisquous/cactbot
