### ISSUE TITLE
Followed instructions  twice but something is wrong still.

### ISSUE THREAD

**Issue by ViolentPudding** [EQAditu/AdvancedCombatTracker#27]
first attempt to install had me keep getting n error about unknown zone or something.

 Went and followed a youtube install(recent vid) for the 2nd attempt and while the youtubers meter worked, mine still just has version data displayed but isnt tracking any combat data."

 Windows 10.

 Any assistance greatly appreciated.

**Comment by EQAditu** [comment]
As there are no official or recommended videos guides existing, I have no idea what you're talking about.

Please review the pinned topic: [Troubleshooting Resources (README)](https://github.com/EQAditu/AdvancedCombatTracker/issues/16)
This is not a support forum.
