### ISSUE TITLE
With update FF online 5.4.1 ACT not working

### ISSUE THREAD

**Issue by Cheester1988** [EQAditu/AdvancedCombatTracker#29]
The update was in the morning. Now not working teh ACT for FF online.

**Comment by Cheester1988** [comment]
The programm is runing, but in the Game no Tracking for a DMG or everthings.

**Comment by EQAditu** [comment]
Every update will break the 3rd party plugin...  which I don't make, so I can't fix.
Also: https://github.com/EQAditu/AdvancedCombatTracker/issues/16
