### ISSUE TITLE
Whilst using ACT encountered issues with the DPS tracker

### ISSUE THREAD

**Issue by WhiteKnight9999** [EQAditu/AdvancedCombatTracker#30]
My DPS tracker, specifically Ember, does not track other characters DPS's. Yet that being said, halfway through an encounter it will begin tracking the healers in my party, which does not give me an accurate tracking of not only my own damage but the other characters in my party as well. Please, someone supply me the assistance I require, I will tell you specifics about my setup and settings of ACT if inquired about it. Thank you.

**Comment by EQAditu** [comment]
You're asking a very niche question in a general place.  This is for the main ACT program*... where as your issue involves ACT->FFXIV->OverlayPlugin->Ember.

This isn't a troubleshooting forum: (read sticky) https://github.com/EQAditu/AdvancedCombatTracker/issues/16
If you think it's Ember specific, go here: https://github.com/GoldenChrysus/ffxiv-ember-overlay
