### ISSUE TITLE
CactbotOverlay & OverlayPlugin not working / reading with FFXIV 5.45 update

### ISSUE THREAD

**Issue by tayconel** [EQAditu/AdvancedCombatTracker#31]
I run the program in administrator. I've uninstalled and reinstalled the program. I've tried to force update Catctbot and Overlay individually. They're both reporting that they have the most up-to-date patches according to the ACT downloader website.

I have other friends who are working fine. So I'm really not sure why mine isn't. Any thoughts or solutions?

**Comment by EQAditu** [comment]
This isn't a troubleshooting forum: (read sticky) https://github.com/EQAditu/AdvancedCombatTracker/issues/16
Also, this appears to be specific to OverlayPlugin/Cactbot which I do not manage or even really use.  I don't think you'll get answered here no matter how long you wait, so read the sticky to get actual support.
