### ISSUE TITLE
ACT window not showing anymore, overlay still works

### ISSUE THREAD

**Issue by NiceManiac** [EQAditu/AdvancedCombatTracker#34]
Hello,

Suddenly when i start ACT the main window does not show up. the overlays work as normal but the main window never shows up, so i cant make any changes to anything.

I do not know what is causing this, and it was just not showing up one day. the day before it worked as it should, but now the window wont show up. i can see DPS information in the overlay plugin but the main window is missing so i cant make changes to the overlay anymore.

I have tried doing a complete reinstall of ACT but the problem still persists.

Plugins:
FFXIV overlay plugin
ACT Hojoring
Cactbot
TTSYukkuri

**Comment by EQAditu** [comment]
First off, this isn't a troubleshooting forum.  See the stickied issue #16 

Check `%APPDATA%\Advanced Combat Tracker\Config\Advanced Combat Tracker.config.xml` for the following:
```xml
<CheckBox Name="cbMinimizeToIcon" Value="False" />
<Form Name="FormActMain" X="224" Y="161" W="1370" H="852" WindowState="Normal" />
```
If you don't know what to do with them, just delete the lines and the defaults will be used.  This shouldn't be necessary if you allowed the uninstaller to delete all config files for your "complete reinstall".

**Comment by NiceManiac** [comment]
Sorry about that, i tried the forums but noone posted a reply for a week on my post there so i tried here as a last resort. 
it seems like somehow the Y value had been set to -1860 so the window was far outside the screen. now everything is working properly.

**Comment by EQAditu** [comment]
I guess I'll apologize as well.  When I first read that post, nothing came to mind... but somehow today I hit the nail on the head.
