### ISSUE TITLE
Linux Version for ACT

### ISSUE THREAD

**Issue by AzkanHawk** [EQAditu/AdvancedCombatTracker#35]
Been looking for a solution for the availability of a fix for it, but can't get things to work on my end. Tried several guides, but generally get a roadblock at certain steps over and over again. Would there fore appreciate it if you could look into this in the future (if you have the time for that). Thank you

Kind regards
Azkan Hawk

**Comment by EQAditu** [comment]
You don't really mention it, but I assume you're talking about usage with FF14.  The FF14 ecosystem is pretty complex... your suggestion would probably require ACT, the FFXIV Plugin and probably OverlayPlugin to be redone.  My understanding from reading the Linux Discord channel is that because FFXIV remains a wine hosted application, that even native Linux programs don't get many advantages.

My main suggestion is to join the [ACT_FFXIV Discord](https://discord.gg/ahFKcmx) and get help from the Linux channel.  I see people getting help there every day, even when they think it's really broken.

**Comment by etherealsauce** [comment]
I am also running on Linux, however my game is EQ2, the problem I have is that I am getting a 403 forbidden on the site. Nobody else has this issue. I have also tried from my mobile device and am blocked there as well.
I know this isn't exactly code/app related, but could not find another means to contact you.

**Comment by etherealsauce** [comment]
speaking of running on linux, eq2 runs quite well with 3.18-staging wine, using playonlinux and vulkan drivers

**Comment by EQAditu** [comment]
This is a really weird thread to report that issue.  
The hosting website is upgrading PHP in probably the most awkward way possible, which is causing the site to be unavailable.

**Comment by etherealsauce** [comment]
I currently work for a hosting company. I see from whois records that the site appears to be hosted on EIG, endurance itnernational group, which is bluehost/hostgator and a few other subsidaries. I recommend hosting somewhere with better support, especially something with cPanel software so it can be managed. I won't say who I work for or recommend a specific company as it might be considered conflict of interest. So, what is exactly happening with php, if you do not mind me asking

**Comment by etherealsauce** [comment]
I threaded here becaue my deployment of act is on linux and I may run into some issues that I would need help with. The most important being to get the exe to start attempting to install. Why isn't the entire installer and such not on the git repo here?

**Comment by EQAditu** [comment]
I got a notification a few months ago that they were removing support for one of the ancient PHP versions.  Like 30 minutes ago cPanel said there were no PHP versions available, now 10 minutes ago 5.6 is available... but the site won't work with that version... so I'm not going to force the 403 errors to go away until 7+ is available again.

> Why isn't the entire installer and such not on the git repo here?

It is...  check the [Releases](https://github.com/EQAditu/AdvancedCombatTracker/releases) page?

**Comment by etherealsauce** [comment]
Agreed, the 403 are probably a result of modsec protecting the site or whatever security is enabled.

Also, duh, thank you for that, not sure why I couldn't find it. downloading now and going to begin testing shortly

**Comment by etherealsauce** [comment]
In wine, I get an error downloading the plugins/titles:
Could not retrieve plugin titles
Error: SecureChannelFailure (The authentication or decryption has failed.)

**Comment by etherealsauce** [comment]
I have seen this error with eq2 maps as well, likely related to the wine setup

**Comment by EQAditu** [comment]
Well, that's ACT relying on the active portion of the website... which as you know, isn't working.  I assume "authentication" in the error message is from the 403 error?  I'm not sure why it wouldn't just say that, though.

**Comment by etherealsauce** [comment]
is there a page to download the plugin and I can manually install it?

**Comment by etherealsauce** [comment]
Hey, by the way, in case you haven't heard this recently, thank you for all you do in every way imaginable! ACT is awesome and we are very grateful you are maintaining it!

**Comment by etherealsauce** [comment]
I am no dev, so ignore me or tell me to eff off if something I say is wrong, I do linux admin stuff. However, shouldn't the app be pulling from the gitrepo?

**Comment by EQAditu** [comment]
The application asks the website where it should get things.  Some things are hosted on the ACT website, some things are hosted on GitHub.  ACT blindly follows what the website says because there's no point in making it smarter than that.

Normally, the EQ2 English parsing plugin is hosted on the ACT website... but [this copy is the same thing](https://raw.githubusercontent.com/EQAditu/AdvancedCombatTracker/master/Plugins/Standalone/ACT_English_Parser.cs).

Every plugin can be manually installed.  My recommendation is to drop this into...  well, I don't know where wine would render this to... but on Windows, `%APPDATA%\Advanced Combat Tracker\Plugins`.  Then in the Plugins tab, just browse to the .cs file and enable it.

**Comment by etherealsauce** [comment]
trying some things, getting errors. hang tight if you can

**Comment by etherealsauce** [comment]
***** 2021-08-25T00:59:16 - Enabling plugin: C:\users\welcomemat\AppData\Advanced Combat Tracker\Plugins\ACT_English_Parser.cs
***** 2021-08-25T00:59:17 - Plugin compilation: ACT_English_Parser.cs
Line: 0 - (CS0006) Metadata file `System.dll' could not be found
Line: 0 - (CS0006) Metadata file `System.Data.dll' could not be found
Line: 0 - (CS0006) Metadata file `System.Linq.dll' could not be found
Line: 0 - (CS0006) Metadata file `System.Drawing.dll' could not be found
Line: 0 - (CS0006) Metadata file `System.Xml.dll' could not be found
Line: 0 - (CS0006) Metadata file `System.Windows.Forms.dll' could not be found

**Comment by etherealsauce** [comment]
I put the file in the recommended relative path mentioned above. The above is output from the playonlinux debugger for simplification.

**Comment by EQAditu** [comment]
Hmm, I wonder if wine isn't prepared for ACT to try compiling its own plugins via API.  Or rather, it seems to be having issues linking to the standard .NET Framework libraries while compiling.  My understanding is that the API just calls csc.exe somehow with the proper parameters for linking.  But the paths are wrong here, or something...

**Comment by etherealsauce** [comment]
This is turning into a rabbit hole of debugging. Need to approach programmatically, will check back.

**Comment by EQAditu** [comment]
Well, if you can't get ACT to compile the .cs plugin, you can use this compiled version...
[ACT_English_Parser.zip](https://github.com/EQAditu/AdvancedCombatTracker/files/7051063/ACT_English_Parser.zip)

**Comment by etherealsauce** [comment]
I was trying this in a fresh prefix for wine, should I have installed .net first. I assume so, thats what it sounds like. I just like to keep that MS stuff to a minimum when can be avoided.

**Comment by etherealsauce** [comment]
I also like the precompiled plan better

**Comment by etherealsauce** [comment]
The precompiled plugin worked flawlessly, Thank you for your efforts. Side note, I am running the app in a separate prefix of wine, which helps isolate the eq2 application.

**Comment by morenathan** [comment]
Would it be possible to get a copy of these precompiled, updated versions?

**Comment by EQAditu** [comment]
Here is an updated version: 
[ACT_English_Parser.zip](https://github.com/user-attachments/files/31609719/ACT_English_Parser.zip)
