### ISSUE TITLE
ACT TTS ignores windows volume settings

### ISSUE THREAD

**Issue by xpdota** [EQAditu/AdvancedCombatTracker#39]
1. Install OverlayPlugin or anything else that would utilize ACT's builtin TTS.
2. Mute ACT's volume in the windows volume mixer.
3. Trigger a TTS.

Expected: You hear nothing
Actual: You hear TTS, even though the volume is muted and the bar is grayed out:
![image](https://user-images.githubusercontent.com/14287379/145703454-27dcd78c-e5f7-48d7-bdad-db57da809f0b.png)

In addition, when merely altering the volume rather than muting, a TTS causes the volume to pop back up to its previous setting.

**Comment by EQAditu** [comment]
This is an artifact of the Windows Media Player API.  It changes the host application's volume to the volume it is instructed to play a sound at.  This cannot be fixed inside of ACT.  You either need to use the volume sliders inside of ACT, or use a sound engine other than WMP API.  (or see if Microsoft wants to fix it)

**Comment by xpdota** [comment]
Looks like this is fixed with the new SAPI setting, thanks!

**Comment by EQAditu** [comment]
Just be aware that playing sound files outside of OverlayPlugin's CEF process will still have this behavior.  The only workaround is to use a different sound engine like Windows API or XAudio2.
