### ISSUE TITLE
Remove Chromatics from plugin list

### ISSUE THREAD

**Issue by logicallysynced** [EQAditu/AdvancedCombatTracker#42]
Hi there,

Could you assist with removing Chromatics from the ACT plugins list? That version that is hosted has been long defunct and not managed anymore, and seems to cause lots of confusion for people.

I haven’t been able to remove it myself as I lost the FTP details provided to me originally.

Let me know if you need any further verification or details.

Thanks!

**Comment by EQAditu** [comment]
No problem.

**Comment by EQAditu** [comment]
Shockingly someone reached out being confused about why it wasn't available in ACT anymore.  I guess you can't please everyone.

**Comment by logicallysynced** [comment]
Wow, it hasn’t even worked for 2-3 years.. can’t believe people are complaining.

I suppose if more people complain you can point them to https://chromaticsffxiv.com , but I would be surprised. :P

**Comment by EQAditu** [comment]
I guess they mentioned something about EQ2.  I'm not sure if that makes a difference about working or not.
