### ISSUE TITLE
Single Instance?

### ISSUE THREAD

**Issue by pigsflew** [EQAditu/AdvancedCombatTracker#43]
Would it be possible to add an option to prevent ACT from opening if another instance is already running, instead foregrounding that instance?

I often realize that I have multiple instances running due to automatically running the program when I start a game that it works on, which is unnecessary.

**Comment by btawa** [comment]
Big fan of this idea.

**Comment by EQAditu** [comment]
New versions of ACT will warn you about multiple instances.  You may fully block new instances by adding the `-onlyone` commandline switch to ACT.  `-skipmutex` will disable the warning and always allow multiple instances.
