### ISSUE TITLE
EQ2 Parsing Issues

### ISSUE THREAD

**Issue by rrichards032** [EQAditu/AdvancedCombatTracker#46]
With the latest patch (4/12/2022), EQ2 devs decided to revamp the way Damage/Heal/Other Numbers are shown in the log messages. 

Example message
- (1649794110)[Tue Apr 12 16:08:30 2022] Commander Goreslaughter hits Finleytwo for 318.7K crushing damage.

**Comment by EQAditu** [comment]
While I will make some changes to support rounded numbers and numbers with thousands separators... I read that you can disable these things in the game client options.  Even after I change the EQ2 parsing plugins, I recommend not using the rounded numbers to give better accuracy.

**Comment by rrichards032** [comment]
Options -> User Interface -> Name and Chat Bubbles: uncheck abbreviated and formatted damage

This mitigates the issue for the short term.

**Comment by EQAditu** [comment]
Can someone try out this version as a beta to see if it correctly handles formatted and/or abbreviated numbers?

https://raw.githubusercontent.com/EQAditu/AdvancedCombatTracker/master/Plugins/Standalone/ACT_English_Parser.cs

**Comment by EQAditu** [comment]
Time will tell if this breaks for users not using en-US culture OSs.

**Comment by EQAditu** [comment]
As far as I know, the newest version of the EQ2 English parsing plugin addresses the issues.
