### ISSUE TITLE
Several Instances??? Tabs?? I dont know how to word it but i only want one i dont know how to delete them

### ISSUE THREAD

**Issue by limebane** [EQAditu/AdvancedCombatTracker#50]
Guys i am really sorry this is informal but i do not see any other person having this probelm i just wanna deleete some tabs!!! i only want one tab see how there are like so many here it sucks!!!! Can anyone help!!!! 
![image](https://user-images.githubusercontent.com/108820381/177587233-35a0b1ad-4b07-47f2-9ad6-9702984d9596.png)

**Comment by EQAditu** [comment]
It looks like you added several overlays to OverlayPlugin.  So you'll have to go there to remove them.  Aside from that, this isn't really the place for this as it doesn't have to do with the main ACT program and this isn't a bug report.

See https://github.com/EQAditu/AdvancedCombatTracker/issues/16

**Comment by limebane** [comment]
awsom thankyou eq    aditu    LOVE!!!!!!!!!!!!!!!
