### ISSUE TITLE
Some mouse buttons not working while using ACT

### ISSUE THREAD

**Issue by Ballantin** [EQAditu/AdvancedCombatTracker#51]
I use ACT for FFXIV log parsing and I also use a Logitech G502 mouse (11 buttons). All my mouse buttons are bound to in-game skills.
When ACT is running some of the buttons are not working. I can some times make them work by ALT+TAB several times between ACT and FFXIV but buttons will stop working again eventually.
As soon as I close ACT all buttons work as expected.

The mouse buttons not working are the two at the top, next to the left click button.

I checked all my ACT and installed plugins configuration for interfering keybindings but none are configured.
I use plugins:
- FFXIV plugin
- Overlay plugin
- Cactbot Overlay plugin

For overlays I have:
- Cactbot
- MopiMopi

**Comment by EQAditu** [comment]
The base ACT program does not use any keyboard hooking, emulation or anything like that.

Please disable all plugins, **_restart ACT_** and try again to see if it continues.  If it does not, I cannot help you as I cannot control what is going on in other plugins.

**Comment by Ballantin** [comment]
I need to keep testing but it seems to be linked to the Overlay plugin.

**Comment by EQAditu** [comment]
Try turning off these options...
![image](https://user-images.githubusercontent.com/52854036/180178648-6ccdc6af-efd8-4558-853e-42c29edfa519.png)
Showing and hiding the windows may be causing focus changes and your mouse software is getting confused by the rapid changes.

Furthermore, try turning on **clickthrough** on all of your overlays so you never click on them and change focus away from the game.  (again, confusing your mouse software)

**Comment by Ballantin** [comment]
That solved the issue, thank you.
