### ISSUE TITLE
Custom Triggers Not Detecting Current Zone

### ISSUE THREAD

**Issue by kaladzz** [EQAditu/AdvancedCombatTracker#56]
I've been seeing quite often an issue where custom triggers will not properly detect the current zone and you'll need to go to the Custom Triggers tab and uncheck/recheck the zone name to get it to properly parse triggers for the current zone or restart ACT. This is happening in Everquest2 at least.

**Comment by kaladzz** [comment]
Did some more testing and was able to identify at least one way to reproduce this issue.

1. Zone character 1 into a zone.
2. Transfer to character 2 and then move into a new zone
3. Transfer back to character 1 and it will detect the correct zone in the title but the triggers for the zone are not activated

It looks like this may be due to closing/opening new log files

**Comment by kaladzz** [comment]
The issue also happens when you aren't switching characters, it seems like it happens if you start ACT after already entering a zone as well and ACT missed the "You have entered message" and detects the zone name by another method. I'm not sure what method it uses if it doesn't see that message but it looks like it doesn't load triggers in that case.

**Comment by kaladzz** [comment]
Also had this happen without switching characters after ACT was already active for some time and already ran several instances. It properly saw the You have entered messages as well. Seems like it just fails to load the custom triggers sometimes for some reason. No errors or anything shown in "Advanced Combat Tracker.log"

**Comment by EQAditu** [comment]
I'm not in a position to be able to recreate the issue and test this, but I will try to add a catch-all method of updating the Custom Triggers list.
