### ISSUE TITLE
Window does not maintain focus when alt-tabbing to ACT #291

### ISSUE THREAD

**Issue by jasonjimmo** [EQAditu/AdvancedCombatTracker#57]
Alt-tabbing to ACT on Windows 10 loses focus of the window, unable to use shortcuts.

Expected results: Alt-tabbing to ACT maintains window focus.

**Comment by EQAditu** [comment]
A Windows program should not need to detect that it has been given focus and hold it from programs that steal it away.  It is the problem of the other program that steals away focus.
