### ISSUE TITLE
Plugin ID request for Zone Change updater for EverQuest

### ISSUE THREAD

**Issue by FreedomFaighter** [EQAditu/AdvancedCombatTracker#83]
[Zone Change Updater](https://github.com/Freemania-Inc/AdvancedEverQuestCombatTrackerEverQuestZoneChangeUpdater)

**Comment by EQAditu** [comment]
ID 94.

I'm hoping you can add a better description for this plugin.  I can make some guesses as to what it does, but would have to look at the code to be sure.  If I have to review the code to understand what it does, then other people would have no clue.

Who is this plugin for?  Why would someone download it?  What does it do?

Those are the sorts of questions that would hopefully be answered by a plugin's description.

**Comment by FreedomFaighter** [comment]
ID needs to point at https://github.com/Freemania/AdvancedCombatTrackerEverQuestZoneChangeUpdater

**Comment by EQAditu** [comment]
I changed this weeks ago, but now the link you gave most recently is a 404 error.  Please provide the proper GitHub repository.

**Comment by FreedomFaighter** [comment]
#85 similar issue
