### ISSUE TITLE
EQRaidAllies plugin id request

### ISSUE THREAD

**Issue by FreedomFaighter** [EQAditu/AdvancedCombatTracker#85]
[EQRaidAllies](https://github.com/Freemania-Inc/AdvancedCombatTrackerEverQuestRaidAllies)

**Comment by EQAditu** [comment]
I wrote about this before... (https://github.com/EQAditu/AdvancedCombatTracker/issues/83#issuecomment-1734392754)
You're not giving required information.

**Comment by FreedomFaighter** [comment]
The purpose of the plugin is explained in the [README.md](https://github.com/Freemania-Inc/AdvancedCombatTrackerEverQuestRaidAllies) of the project

**Comment by FreedomFaighter** [comment]
After a couple of bug fixes:

The RaidAllies plugin loads the raid roster file from the raid window into the ACT application and sets the current encounter allies in the application from the text file.  Allies are shown after the read and listed in a listBox.

**Comment by EQAditu** [comment]
The new ID is 96.  

I also added the hosted description of 94 for when it becomes visible.

**Comment by FreedomFaighter** [comment]
ID was added to and builds in [EQRA pull request 7](https://github.com/Freemania-Inc/AdvancedCombatTrackerEverQuestRaidAllies/pull/7)

**Comment by FreedomFaighter** [comment]
ID needs to be updated to point at https://github.com/Freemania/AdvancedCombatTrackerEverQuestRaidAllies

**Comment by EQAditu** [comment]
I changed this weeks ago, but now the link you gave most recently is a 404 error.  Please provide the proper GitHub repository.

**Comment by FreedomFaighter** [comment]
This may of caused some sort of MITM meta data edit closing for now and updates will come from my page
