### ISSUE TITLE
The row data for the AttackType column doesn't seem to be appearing

### ISSUE THREAD

**Issue by mastk0** [EQAditu/AdvancedCombatTracker#93]
As shown in the screenshot, it seems that Japanese language support is not functioning properly, as the row data for the AttackType column is not being displayed. However, when performing a right-click to copy as CSV, it is evident that the Japanese action names are correctly included.

<img width="1097" alt="0001_edit" src="https://github.com/EQAditu/AdvancedCombatTracker/assets/156874970/3d8cb6f8-98bc-4af7-852c-fb2333d4c927">

```
EncId,STime,RelativeTime,Attacker,SwingType,AttackType,DamageType,Victim,Damage,DamageString,Critical,CriticalStr,Special,StatusDuration,OverHeal,DirectHit
214a73ef,2024-01-17 13:08:31,2.008,YOU,8,ルインジャ実行可,,YOU,0,No Damage,F,None,None,60,0,
214a73ef,2024-01-17 13:08:32,3.39,YOU,2,ルインジャ,Magic,木人,33037,33_037,T,None,None,,0,True
214a73ef,2024-01-17 13:08:29,0,YOU,2,ルインガ,Magic,木人,11646,11_646,F,None,None,,0,
214a73ef,2024-01-17 13:08:31,2.676,YOU,2,ミアズマバースト,Magic,木人,13204,13_204,F,None,None,,0,
214a73ef,2024-01-17 13:08:31,2.008,YOU,2,エナジードレイン,Magic,木人,9515,9_515,F,None,None,,0,True
214a73ef,2024-01-17 13:08:31,2.676,YOU,8,エーテルフロー,,YOU,0,No Damage,F,None,None,9999,0,
214a73ef,2024-01-17 13:08:31,2.008,YOU,8,エーテルフロー,,YOU,0,No Damage,F,None,None,9999,0,
```

**Comment by mastk0** [comment]
Similarly, the 'Victim' field was affected. While 'You' is visible, '木人' is not displayed, indicating a high possibility of a Japanese language-related issue.

**Comment by EQAditu** [comment]
Likely this is a font rendering problem in GDI+.

Could you export a *.act file and attach it here for me to test with?

Also, I need to know what font you're currently using.  The least error prone way is to get it from the config file line.  It will look something like the following near the bottom of the file:
```xml
<FontColorControl Name="fccDataGrid" ForeColor="-1447447" BackColor="-15790319" Font="Calibri Light" Style="Regular" Size="9.75" />
```

It looks like you have some custom DPI scaling happening, but I don't think that's the issue.

**Comment by mastk0** [comment]
I couldn't figure out how to export the *.act file. However, upon hearing about the DPI issue, I tried the following, and the problem was resolved. Thank you!

Compatibility of Advanced Combat Tracker.exe → Change DPI settings to High → Set 'Override high DPI scaling behavior' to 'Application' as shown in the screenshot, under 'Scaling performed by:'
<img width="281" alt="スクリーンショット 2024-01-18 110958" src="https://github.com/EQAditu/AdvancedCombatTracker/assets/156874970/77b5fa23-ad6d-454e-bc93-d6ba4c703fad">
<img width="1106" alt="0002" src="https://github.com/EQAditu/AdvancedCombatTracker/assets/156874970/35ab198c-f7d0-4e4e-a25c-02a2433f68e8">


Reference information:
・ACT settings remain at their default configuration. (Fonts and colors have all been reset)
・OS is Windows 11 23H2 (OS Build 22631.3007)
・The monitor used is a 4K display.

**Comment by EQAditu** [comment]
It would have been the following: 
![image](https://github.com/EQAditu/AdvancedCombatTracker/assets/52854036/e55f9208-2b33-4a4e-93f9-789bb10c6826)

I wonder why the DPI scaling would make things invisible, though.  I noticed that the Latin letters were rather too big for the rows, which made me think of DPI scaling to begin with...  I wonder if katakana/kanji needed more room to render vertically at that font size... and the layout decided to push it to another line that didn't show up?

**Comment by mastk0** [comment]
The *.act file is here. Does this seem sufficient for reproduction?

[MultipleEncounters.zip](https://github.com/EQAditu/AdvancedCombatTracker/files/13972675/MultipleEncounters.zip)

**Comment by EQAditu** [comment]
This problem appears to be specific to running Hojoring plugins.  They load the WPF UI framework into ACT which overrides how DPI settings are handled.  When DPI settings are at default, this issue appears.  Overriding DPI settings like you have done will fix this issue.  Not using Hojoring will also fix this issue no matter what DPI settings are used.

Maybe having ACT include DPI aware overrides will help, but I'm concerned this will change how ACT looks for some people when they were not expecting it.

**Comment by mastk0** [comment]
I appreciate the investigation. I do have Hojoring installed, so that's probably the cause. As long as I know the reason, it's fine!

**Comment by EQAditu** [comment]
ACT's manifest now sets a DPI scaling mode so overrides shouldn't be necessary.
