### ISSUE TITLE
ACT v3.4.6 crashing on startup

### ISSUE THREAD

**Issue by Midi-In** [EQAditu/AdvancedCombatTracker#96]
Application version: v3.4.6
OS: Windows 8.1 Home Edition
.NET Framework version: 4.6.00081

The application crashes on startup with errors as follow (attached images):
![mmc_2024-03-06_12-42-08](https://github.com/EQAditu/AdvancedCombatTracker/assets/42059764/29ab4bec-f0d6-42b1-9893-eb68a558e03b)
![mmc_2024-03-06_12-41-52](https://github.com/EQAditu/AdvancedCombatTracker/assets/42059764/e7134b80-8cac-4708-a3bb-fb517d31bb74)
![explorer_2024-03-06_12-40-06](https://github.com/EQAditu/AdvancedCombatTracker/assets/42059764/75372a2e-d615-44a2-a680-185896fb5b46)

**Comment by Midi-In** [comment]
Does anyone even read these issues?

**Comment by EQAditu** [comment]
Occasionally.  But considering the time passed and no one else ever reporting this issue, it tends to make me think that this is not a bug in ACT but an idiosyncrasy in your setup which is about troubleshooting.  I have tried to state clearly that GitHub is not to be used for general discussions nor troubleshooting.  (#16)
![image](https://github.com/EQAditu/AdvancedCombatTracker/assets/52854036/5343254d-2e64-4212-9d18-abc70d1cf3a4)

When people ignore that, I don't feel very motivated to break with my policy and respond to them.  If more people report the same issue, I would then take it seriously.

I hate to reward bad behavior, but I'll respond anyways.  You're missing critical files from your ACT folder that a normal installation would have.  Reinstall to reobtain those files.  (Also don't use ACTx86 unless you have a specific reason to)  If there are any other issues, they would be covered up by this problem.

**Comment by Midi-In** [comment]
I wasn't aware that i posted about this issue in a wrong place. As for the installation, this is right after clean install inside a directory in %userprofile%/desktop. I'm using an older version because of issues with upgrading NET Framework past v.3.4.6 on Windows 8.1. I'm not sure what is the last ACT release to support that version. I will move this topic to the forums so you can close this issue now.

**Comment by EQAditu** [comment]
It looks like you used an update package which does not contain all files of a full installation.  Use a normal full installation **first**... then you can mess with the version after that.  

You can modify `Advanced Combat Tracker.exe.config` with a text editor and trick it into using other .NET Framework versions, but without 4.6, ACT will not be able to use HTTPS on secure sites to update or download plugins.  Before 4.6 is too old to use more secure standards that are in use today.

**Comment by Midi-In** [comment]
Thank you so much, it's working now!
