### ISSUE TITLE
ACT Triggers can be heared by other ppl in Discord Vc

### ISSUE THREAD

**Issue by PotatoSalado** [EQAditu/AdvancedCombatTracker#98]
Last time after raiding this week i got told by 3 Static members that they heared the ACT Trigger lines i have set for myself as tts for specific raid mechanics o.o
However when i tried to replicate this with a friend, it didn't happen.
Also one of the friends doesn't use act or any plugins and mods at all, one does have the same triggers and the last one don't use triggers.

So is it even possible that this can happen??

**Comment by EQAditu** [comment]
This isn't really a support forum.  #16 

You'd have to figure out your own audio devices on your computer and know which ones Discord listens to and if you have any routing in Windows to have an input listen to any of your output devices.  This has nothing to do with ACT but is Windows audio troubleshooting.  You can certainly make this happen in Windows but ACT plays no part in configuring it.
